/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as FormRouteImport } from './routes/form'
import { Route as ResourceResourceRouteImport } from './routes/_resource/resource'
import { Route as ResourceModalResourceRouteImport } from './routes/_resource/modalResource'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceResourceRoute = ResourceResourceRouteImport.update({
  id: '/_resource/resource',
  path: '/resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceModalResourceRoute = ResourceModalResourceRouteImport.update({
  id: '/_resource/modalResource',
  path: '/modalResource',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/form': typeof FormRoute
  '/table': typeof TableRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/modalResource': typeof ResourceModalResourceRoute
  '/resource': typeof ResourceResourceRoute
}
export interface FileRoutesByTo {
  '/form': typeof FormRoute
  '/table': typeof TableRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/modalResource': typeof ResourceModalResourceRoute
  '/resource': typeof ResourceResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/form': typeof FormRoute
  '/table': typeof TableRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_resource/modalResource': typeof ResourceModalResourceRoute
  '/_resource/resource': typeof ResourceResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/form'
    | '/table'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/modalResource'
    | '/resource'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/form'
    | '/table'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/modalResource'
    | '/resource'
  id:
    | '__root__'
    | '/form'
    | '/table'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_resource/modalResource'
    | '/_resource/resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FormRoute: typeof FormRoute
  TableRoute: typeof TableRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ResourceModalResourceRoute: typeof ResourceModalResourceRoute
  ResourceResourceRoute: typeof ResourceResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/resource': {
      id: '/_resource/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof ResourceResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resource/modalResource': {
      id: '/_resource/modalResource'
      path: '/modalResource'
      fullPath: '/modalResource'
      preLoaderRoute: typeof ResourceModalResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FormRoute: FormRoute,
  TableRoute: TableRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ResourceModalResourceRoute: ResourceModalResourceRoute,
  ResourceResourceRoute: ResourceResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
